export default function About() {
    const endpoints = [
        { method: 'GET', path: '/api/v1/health', desc: 'Health check — confirm API is alive' },
        { method: 'GET', path: '/api/v1/tasks', desc: 'Get all tasks. Supports ?completed=true|false and ?priority=high|medium|low' },
        { method: 'GET', path: '/api/v1/tasks/:id', desc: 'Get a single task by its MongoDB ObjectID' },
        { method: 'POST', path: '/api/v1/tasks', desc: 'Create a new task (title required)' },
        { method: 'PUT', path: '/api/v1/tasks/:id', desc: 'Full replacement update of a task' },
        { method: 'PATCH', path: '/api/v1/tasks/:id', desc: 'Partial update (e.g. toggle completed)' },
        { method: 'DELETE', path: '/api/v1/tasks/:id', desc: 'Permanently delete a task' },
    ];

    const schema = [
        { field: '_id', type: 'ObjectId', note: 'Auto-generated by MongoDB' },
        { field: 'title', type: 'String', note: 'Required · max 120 chars' },
        { field: 'description', type: 'String', note: 'Optional' },
        { field: 'priority', type: 'Enum', note: '"low" | "medium" | "high"  (default: medium)' },
        { field: 'completed', type: 'Boolean', note: 'Default: false' },
        { field: 'createdAt', type: 'Date', note: 'Auto-managed by Mongoose timestamps' },
        { field: 'updatedAt', type: 'Date', note: 'Auto-managed by Mongoose timestamps' },
    ];

    return (
        <div>
            <div className="page-header">
                <h1>API Documentation</h1>
                <p>Reference guide for the Task Manager REST API consumed by this app.</p>
            </div>

            {/* Base URL */}
            <div className="card" style={{ marginBottom: '1.5rem' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.75rem', flexWrap: 'wrap' }}>
                    <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)', fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                        Base URL
                    </span>
                    <code>http://localhost:5001/api/v1</code>
                    <span style={{ fontSize: '0.78rem', color: 'var(--text-muted)' }}>— All endpoints are relative to this.</span>
                </div>
            </div>

            {/* Endpoints */}
            <div className="card" style={{ marginBottom: '1.5rem', padding: 0, overflow: 'hidden' }}>
                <div style={{ padding: '1.25rem 1.4rem', borderBottom: '1px solid var(--border)' }}>
                    <h2 style={{ fontSize: '1rem', fontWeight: 700 }}>📡 Endpoints</h2>
                </div>
                <table className="endpoint-table">
                    <thead>
                        <tr>
                            <th>Method</th>
                            <th>Path</th>
                            <th>Description</th>
                        </tr>
                    </thead>
                    <tbody>
                        {endpoints.map((ep) => (
                            <tr key={ep.path + ep.method}>
                                <td>
                                    <span className={`method-badge method-${ep.method.toLowerCase()}`}>
                                        {ep.method}
                                    </span>
                                </td>
                                <td><code>{ep.path}</code></td>
                                <td>{ep.desc}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* Schema */}
            <div className="card" style={{ marginBottom: '1.5rem', padding: 0, overflow: 'hidden' }}>
                <div style={{ padding: '1.25rem 1.4rem', borderBottom: '1px solid var(--border)' }}>
                    <h2 style={{ fontSize: '1rem', fontWeight: 700 }}>🏗️ Task Schema</h2>
                </div>
                <table className="endpoint-table">
                    <thead>
                        <tr>
                            <th>Field</th>
                            <th>Type</th>
                            <th>Notes</th>
                        </tr>
                    </thead>
                    <tbody>
                        {schema.map((s) => (
                            <tr key={s.field}>
                                <td><code>{s.field}</code></td>
                                <td style={{ color: 'var(--accent)', fontWeight: 600 }}>{s.type}</td>
                                <td>{s.note}</td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* Example payloads */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))', gap: '1rem', marginBottom: '1.5rem' }}>
                {/* Create */}
                <div className="card">
                    <h3 style={{ fontSize: '0.88rem', fontWeight: 700, marginBottom: '0.75rem', color: 'var(--text-secondary)' }}>
                        <span className="method-badge method-post">POST</span>&nbsp; Create Task Body
                    </h3>
                    <pre style={{
                        background: 'var(--bg-primary)', borderRadius: 'var(--radius-sm)',
                        padding: '1rem', fontSize: '0.78rem', color: '#a5b4fc',
                        border: '1px solid var(--border)', overflowX: 'auto', lineHeight: 1.6,
                    }}>
                        {`{
  "title": "Build auth module",
  "description": "JWT-based login flow",
  "priority": "high",
  "completed": false
}`}
                    </pre>
                </div>

                {/* Success response */}
                <div className="card">
                    <h3 style={{ fontSize: '0.88rem', fontWeight: 700, marginBottom: '0.75rem', color: 'var(--text-secondary)' }}>
                        <span className="method-badge method-get">201</span>&nbsp; Response Shape
                    </h3>
                    <pre style={{
                        background: 'var(--bg-primary)', borderRadius: 'var(--radius-sm)',
                        padding: '1rem', fontSize: '0.78rem', color: '#a5b4fc',
                        border: '1px solid var(--border)', overflowX: 'auto', lineHeight: 1.6,
                    }}>
                        {`{
  "success": true,
  "data": {
    "_id": "64d8a1e2...",
    "title": "Build auth module",
    "priority": "high",
    "completed": false,
    "createdAt": "...",
    "updatedAt": "..."
  }
}`}
                    </pre>
                </div>

                {/* Error */}
                <div className="card">
                    <h3 style={{ fontSize: '0.88rem', fontWeight: 700, marginBottom: '0.75rem', color: 'var(--text-secondary)' }}>
                        <span className="method-badge method-delete">400</span>&nbsp; Error Response
                    </h3>
                    <pre style={{
                        background: 'var(--bg-primary)', borderRadius: 'var(--radius-sm)',
                        padding: '1rem', fontSize: '0.78rem', color: '#fca5a5',
                        border: '1px solid var(--border)', overflowX: 'auto', lineHeight: 1.6,
                    }}>
                        {`{
  "success": false,
  "error": "title is required"
}`}
                    </pre>
                </div>
            </div>

            {/* Tech stack */}
            <div className="card">
                <h2 style={{ fontSize: '1rem', fontWeight: 700, marginBottom: '1rem' }}>🛠️ Tech Stack</h2>
                <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))', gap: '0.75rem' }}>
                    {[
                        { name: 'React 18', role: 'Frontend UI framework', icon: '⚛️' },
                        { name: 'React Router v6', role: 'Client-side routing', icon: '🗺️' },
                        { name: 'Axios', role: 'HTTP client & API calls', icon: '📡' },
                        { name: 'Vite', role: 'Build tool & dev server', icon: '⚡' },
                        { name: 'Node.js + Express', role: 'REST API backend', icon: '🟢' },
                        { name: 'MongoDB + Mongoose', role: 'Database & ODM', icon: '🍃' },
                    ].map((t) => (
                        <div key={t.name} style={{
                            background: 'var(--bg-primary)', border: '1px solid var(--border)',
                            borderRadius: 'var(--radius-sm)', padding: '0.85rem 1rem',
                        }}>
                            <div style={{ fontSize: '1.3rem', marginBottom: '0.3rem' }}>{t.icon}</div>
                            <div style={{ fontWeight: 700, fontSize: '0.88rem', marginBottom: '0.15rem' }}>{t.name}</div>
                            <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>{t.role}</div>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    );
}
